name: coffee_app
description: My Coffee Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  coffee_repository:
    path: packages/coffee_repository
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
