name: coffee_repository
description: A repository that handles coffee related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  coffee_data_sources:
    path: ../coffee_data_sources
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  coffee_api_client:
    path: ../coffee_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.0
