name: monitoring_repository
description: A repository that manages monitoring services like Analytics and Crashlytics.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
